baseURL = "https://standbild.kollegen.uber.space"
languageCode = 'de-de'
title = 'Standbild'
theme = 'gallery'

copyright = "Â© Christian Schulzendorff"
defaultContentLanguage = "de"
disableKinds = []
enableRobotsTXT = true
timeZone = "Europe/Berlin"
timeout = "120s"

[params]
  defaultTheme = "dark"
  description = "Bilder in Alben"
  [params.author]
    email = "chs8691+standbild@mailbox.org"
    name = "Christian Schulzendorff"
  [params.socialIcons]
    github = "https://github.com/chs8691/standbild/"
    email = "mailto:chs8691+standbild@mailbox.org"
    website = "https://kollegen.uber.space"
    flickr = "https://www.flickr.com/photos/christian_schulzendorff/"
  [params.meta]
    favicon = true

  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 77
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = false
    includeFields = "ImageDescription|Orientation"

[menu]
  [[menu.footer]]
    name = "Impressum"
    url = "https://kollegen.uber.space/impressum/"
    weight = 3
  [[menu.footer]]
    name = "kollegen.uber.space"
    url = "https://kollegen.uber.space"
    weight = 4

[services]
  [services.rss]
    limit = 100

[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50


[taxonomies]
  year = 'year'
  filmsimulation = 'filmsimulation'
  model = 'model'
  lens = 'lens'
  recipe = 'recipe'
